# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-04 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20171102_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='Image',
            new_name='image',
        ),
    ]
